// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';

export function GetGameFiles(arg1:string):Promise<void>;

export function GetVersions():Promise<Array<download.Version>>;

export function StartApp():Promise<void>;

export function StartLogin():Promise<void>;
