// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameFiles(arg1) {
  return window['go']['main']['App']['GetGameFiles'](arg1);
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function StartApp() {
  return window['go']['main']['App']['StartApp']();
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}
