// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameFiles():Promise<void>;

export function StartApp():Promise<void>;

export function StartLogin():Promise<void>;
