// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInstance(arg1, arg2) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function GetInstanceInfo(arg1) {
  return window['go']['main']['App']['GetInstanceInfo'](arg1);
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function StartApp() {
  return window['go']['main']['App']['StartApp']();
}

export function StartGame(arg1) {
  return window['go']['main']['App']['StartGame'](arg1);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function UpdateMem(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMem'](arg1, arg2, arg3);
}
