// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {instances} from '../models';
import {download} from '../models';

export function CreateInstance(arg1:string,arg2:string):Promise<instances.Instance>;

export function DeleteInstance(arg1:string):Promise<boolean>;

export function GetInstanceInfo(arg1:string):Promise<instances.Instance>;

export function GetVersions():Promise<Array<download.Version>>;

export function ListInstances():Promise<Array<instances.Instance>>;

export function Logout():Promise<void>;

export function StartApp():Promise<void>;

export function StartGame(arg1:string):Promise<void>;

export function StartLogin():Promise<void>;

export function UpdateMem(arg1:string,arg2:number,arg3:number):Promise<void>;
