// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMinecraftAuth(arg1, arg2) {
  return window['go']['main']['Auth']['GetMinecraftAuth'](arg1, arg2);
}

export function GetOAuthCode() {
  return window['go']['main']['Auth']['GetOAuthCode']();
}

export function GetXBL(arg1) {
  return window['go']['main']['Auth']['GetXBL'](arg1);
}

export function GetXSTS(arg1) {
  return window['go']['main']['Auth']['GetXSTS'](arg1);
}

export function PollOAuthCode(arg1) {
  return window['go']['main']['Auth']['PollOAuthCode'](arg1);
}

export function RefreshMinecraftToken(arg1) {
  return window['go']['main']['Auth']['RefreshMinecraftToken'](arg1);
}

export function SaveKeysToJson(arg1) {
  return window['go']['main']['Auth']['SaveKeysToJson'](arg1);
}
