// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAccountInfo(arg1:main.MinecraftPayload):Promise<main.MinecraftInfo>;

export function GetMinecraftAuth(arg1:main.XSTSPayload,arg2:main.XBLPayload):Promise<main.MinecraftPayload>;

export function GetOAuthCode():Promise<main.MicrosoftOAuthPayload>;

export function GetXBL(arg1:main.MicrosoftAccessToken):Promise<main.XBLPayload>;

export function GetXSTS(arg1:main.XBLPayload):Promise<main.XSTSPayload>;

export function PollOAuthCode(arg1:main.MicrosoftOAuthPayload):Promise<main.MicrosoftAccessToken>;

export function RefreshMinecraftToken(arg1:main.MicrosoftAccessToken):Promise<main.MinecraftPayload>;

export function SaveAccountInfo(arg1:main.MinecraftInfo):Promise<boolean>;

export function SaveKeysToJson(arg1:main.AuthSession):Promise<boolean>;
