// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMinecraftAuth():Promise<void>;

export function GetOAuthCode():Promise<main.MicrosoftOAuthPayload>;

export function GetXBL(arg1:main.MicrosoftAccessToken):Promise<main.XBLPayload>;

export function GetXSTS(arg1:main.XBLPayload):Promise<main.XSTSPayload>;

export function PollOAuthCode(arg1:main.MicrosoftOAuthPayload):Promise<main.MicrosoftAccessToken>;
