// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMinecraftAuth() {
  return window['go']['main']['Auth']['GetMinecraftAuth']();
}

export function GetOAuthCode() {
  return window['go']['main']['Auth']['GetOAuthCode']();
}

export function GetXBL(arg1) {
  return window['go']['main']['Auth']['GetXBL'](arg1);
}

export function GetXSTS(arg1) {
  return window['go']['main']['Auth']['GetXSTS'](arg1);
}

export function PollOAuthCode(arg1) {
  return window['go']['main']['Auth']['PollOAuthCode'](arg1);
}
